apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service-deployment
  labels:
    env: development
    tier: backend
    app: member-service
spec:
  replicas: 1
  selector:
    matchLabels:
      env: development
      tier: backend
      app: member-service
  template:
    metadata:
      labels:
        env: development
        tier: backend
        app: member-service
    spec:
      containers:
        - name: member-service
          image: plog-registry.kr.ncr.ntruss.com/songspasssta-plog-storage:member-service-1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: TZ

            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SERVER_PORT

            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MEMBER_POSTGRES_HOST

            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: POSTGRES_PORT

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MEMBER_POSTGRES_DB

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: REDIS_PORT

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_PASSWORD

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: REDIS_PASSWORD

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: JWT-SECRET-KEY

# readinessProbe:
#   httpGet:
#     path: /actuator/health
#     port: 8080 # production 환경 -> 80
#   initialDelaySeconds: 10
#   periodSeconds: 5
#   successThreshold: 1
#   failureThreshold: 3
