apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: apigateway-ingress
  labels:
    env: development
    tier: backend
    app: apigateway
spec:
  rules:
    - host: <개발 환경 API 게이트웨이 도메인> # TODO
      http:
        paths:
          - path: /
            backend:
              serviceName: apigateway
              servicePort: 8000
