apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service-deployment
  labels:
    env: development
    tier: backend
    app: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      env: development
      tier: backend
      app: report-service
  template:
    metadata:
      labels:
        env: development
        tier: backend
        app: report-service
    spec:
      containers:
        - name: report-service
          image: plog-registry.kr.ncr.ntruss.com/songspasssta-plog-storage:report-service-1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: TZ

            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SERVER_PORT

            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: POSTGRES_HOST

            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: POSTGRES_PORT

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_PASSWORD

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: REDIS_PORT

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: REDIS_PASSWORD

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: JWT-SECRET-KEY

            - name: NCLOUD_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: NCLOUD-ENDPOINT

            - name: NCLOUD_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: NCLOUD-ACCESS-KEY

            - name: NCLOUD_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: NCLOUD-SECRET-KEY

            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: S3-BUCKET

            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: S3-ACCESS-KEY

            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: S3-SECRET-KEY

# readinessProbe:
#   httpGet:
#     path: /actuator/health
#     port: 8080
#   initialDelaySeconds: 10
#   periodSeconds: 5
#   successThreshold: 1
#   failureThreshold: 3
