apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service-deployment
  labels:
    env: development
    tier: backend
    app: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      env: development
      tier: backend
      app: report-service
  template:
    metadata:
      labels:
        env: development
        tier: backend
        app: report-service
    spec:
      containers:
        - name: report-service
          image: songspasssta-plog-storage/report-service:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: report-database-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: report-database-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: report-database-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: report-database-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: report-database-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
