apiVersion: apps/v1
kind: Deployment
metadata:
  name: plogging-service-deployment
  labels:
    env: development
    tier: backend
    app: plogging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      env: development
      tier: backend
      app: plogging-service
  template:
    metadata:
      labels:
        env: development
        tier: backend
        app: plogging-service
    spec:
      containers:
        - name: plogging-service
          image: plog-registry.kr.ncr.ntruss.com/songspasssta-plog-storage:plogging-service-1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: config  # ConfigMap에서 TZ 값을 가져옴
                  key: TZ
            - name: SERVER_PORT
              value: "8080"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: PLOGGING_POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: PLOGGING_POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_PASSWORD
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 10
#            periodSeconds: 5
#            successThreshold: 1
#            failureThreshold: 3
